### ISSUE TITLE
TypeError: __init__() takes at most 14 arguments (15 given)

### ISSUE THREAD

**Issue by phonism** [Far0n/kaggle-lmgpip#1]
I compile the code, and there is a error in xgbex.py, I can't figure out how to fix it.
Here is the traceback.
OS: OS X 10.11.1
XGBoost: 0.4.0 built from source.

```
Traceback (most recent call last):
  File "learn.py", line 103, in <module>
    **xgb_params_linear)],
  File "/path/to/kaggle-lmgpip/xgbex.py", line 26, in __init__
    base_score, seed, missing)
TypeError: __init__() takes at most 14 arguments (15 given)
```

**Comment by Far0n** [comment]
Is your xgb the tagged 0.4 release version? If so, it's probably too old and you should checkout the most recent sources.
